# Generated by Django 5.2.4 on 2025-07-23 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Brand',
            new_name='brand',
        ),
    ]
