name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      python-version: 3.12

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies with uv
        uses: astral-sh/setup-uv@v1
        with:
          uv-version: 0.6.10
      - run: uv pip sync
      - run: uv run ruff check
      - run: uv run ruff format --check
